from testcontainers.mysql import MySqlContainer
import sqlalchemy

import pathlib

fields = "COLLATION_NAME  CHARACTER_SET_NAME  ID  IS_DEFAULT  IS_COMPILED SORTLEN PAD_ATTRIBUTE"
lines = [
"'''Dont' edit, this file was generated by devtools/gen-collations.py or run by rye run gencols'''",
"",
"from collections import namedtuple",
f'collation = namedtuple("collation", {repr(fields)})',
f'''def get_collation_by_id(colid):
    return collations_mapper.get(colid, None)'''

]

from collections import namedtuple
collation = namedtuple("collation", fields)

with MySqlContainer("mysql:8.0.35") as mysql:
    engine = sqlalchemy.create_engine(mysql.get_connection_url())
    with engine.begin() as conn:
        collations_result = conn.execute(
            sqlalchemy.text("show collation;")
        ).fetchall()
        m = {}
        for c in collations_result:
            col = collation(*c)
            m[int(col.ID)] = col

        lines.append(f'collations_mapper = {repr(m)}')

current = pathlib.Path(__file__)
with open(current.parent.parent / "pyinnodb" / "const" / "collations.py", "w") as f:
    f.write("\n".join(lines))
