name: hello
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION=-y bash
        source ~/.rye/env
        ls
        rye list
