name: hello
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: run build
      run: |
        curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION=-y bash
        source ~/.rye/env
        rye sync
        rye tools install uv
        rye run of
        git status
        ls
