name: version
on:
  push:
    branches: [ feature/version ]
  pull_request:
    branches: [ main ]
    types: [ closed ]


jobs:
  bump_version_and_tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: run build
      run: |
        curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION=-y bash
        source ~/.rye/env
        git show HEAD pyproject.toml | grep version
        if [ -z $? ]
        then
          echo "should_tag=true" >> $GITHUB_OUTPUT
          NEW_VERSION=v`rye version`
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        else
          echo "should_tag=true" >> $GITHUB_OUTPUT
        fi
    - name: Create GitHub Tag
      if: steps.version-check.outputs.should_tag == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const version = '${{ steps.version-check.outputs.new_version }}';
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/v${version}`,
            sha: '${{ github.event.pull_request.merge_commit_sha }}'
          })
